# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('motto', models.CharField(max_length=40)),
                ('leader', models.CharField(max_length=40)),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.House')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=50)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.House')),
            ],
        ),
    ]
