# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161010_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='img',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
