# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_house_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('motto', models.CharField(max_length=40)),
                ('leader', models.CharField(max_length=40)),
                ('img', models.CharField(default=1, max_length=300)),
                ('name', models.CharField(max_length=45)),
                ('rival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SmallHouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
