# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161011_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='minors',
            field=models.ManyToManyField(blank=True, to='app.SmallHouse'),
        ),
    ]
