# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_region_minors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='minors',
        ),
        migrations.AddField(
            model_name='smallhouse',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
        ),
    ]
